# Use a recent version of the Compose file format
version: '3.8'

services:
  # Define your application service, you can name it anything (e.g., 'app', 'streamlit-app')
  apic_app:
    # Tell Compose to build the image from the Dockerfile in the current directory (.)
    build: .
    # Define port mappings: map port 8501 on your host machine to port 8501 in the container
    ports:
      - "8501:8501"